# Generated by Django 3.1.2 on 2020-10-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberapp', '0001_initial'),
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateTimeField()),
                ('screen_num', models.IntegerField()),
                ('seat_name', models.CharField(max_length=10)),
                ('movie_detail_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movieapp.moviedetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberapp.profile')),
                ('schedule_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buyapp.schedulemodel')),
            ],
        ),
    ]
