# Generated by Django 3.1.2 on 2020-10-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('release', models.DateTimeField()),
                ('running_time', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('cast', models.TextField()),
                ('show_flg', models.CharField(max_length=20)),
                ('resting', models.CharField(max_length=10)),
            ],
        ),
    ]
