# Generated by Django 3.1.2 on 2020-10-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetailmodel',
            name='videos',
            field=models.CharField(default='nul', max_length=100),
            preserve_default=False,
        ),
    ]
